refactor code
KodyPay/kody-clientsdk-python pull request #20
Opened 2024-12-30 09:17 UTC by timmycheung-kody

## **Associated JIRA tasks**

Links to associated JIRAs for this project

## **What the code does.**

Describe what the code change is and what functionality it adds.

## **Does this code change break backwards compatibility?.**

Describe where and how this code change breaks backwards compatibility.

2025-01-07 10:31 UTC, 7kfpun requested changes

2025-01-07 10:31 UTC, 7kfpun commented on versions/3_12/samples/ecom/get_payment_details.py
> +    address = "grpc-staging.kodypay.com"
Update the README as well? Looks not correct with your new updates
https://github.com/KodyPay/kody-clientsdk-python/tree/main/versions/3_12/samples#readme

2025-01-14 08:51 UTC, sishbi approved these changes
LGTM

2025-01-14 09:19 UTC, sishbi approved these changes
LGTM

2025-01-15 11:00 UTC, merged